default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cafe_bell_o_development
  username: erictodasco
  password: 
  host: localhost

test:
  <<: *default
  database: cafe_bell_o_test
  username: erictodasco
  password: 
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
